// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogPostDocumentDataSlicesSlice = HeroSlice;

/**
 * Item in *Blog Post → sections*
 */
export interface BlogPostDocumentDataSectionsItem {
  /**
   * heading field in *Blog Post → sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sections[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * paragraph field in *Blog Post → sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sections[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * image field in *Blog Post → sections*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sections[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Catch Hook
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * headline field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.headline
   * - **Tab**: Catch Hook
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.image
   * - **Tab**: Catch Hook
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Catch Hook
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * sections field in *Blog Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sections[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  sections: prismic.GroupField<Simplify<BlogPostDocumentDataSectionsItem>>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

/**
 * Content for CategoryLink documents
 */
interface CategorylinkDocumentData {
  /**
   * Title field in *CategoryLink*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categorylink.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *CategoryLink*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categorylink.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *CategoryLink*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categorylink.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * CategoryLink document from Prismic
 *
 * - **API ID**: `categorylink`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategorylinkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategorylinkDocumentData>,
    "categorylink",
    Lang
  >;

type ComingSoonDocumentDataSlicesSlice =
  | SocialMediaLinksSlice
  | HeroSlice
  | CallToActionSlice;

/**
 * Content for Coming Soon documents
 */
interface ComingSoonDocumentData {
  /**
   * Slice Zone field in *Coming Soon*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: coming_soon.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ComingSoonDocumentDataSlicesSlice> /**
   * Meta Description field in *Coming Soon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: coming_soon.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Coming Soon*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coming_soon.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Coming Soon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: coming_soon.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Coming Soon document from Prismic
 *
 * - **API ID**: `coming_soon`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ComingSoonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ComingSoonDocumentData>,
    "coming_soon",
    Lang
  >;

/**
 * Item in *Content → features*
 */
export interface ContentDocumentDataFeaturesItem {
  /**
   * image field in *Content → features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.features[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Content → features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.features[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Content → features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.features[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * headline field in *Content → features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.features[].headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;
}

/**
 * Content for Content documents
 */
interface ContentDocumentData {
  /**
   * features field in *Content*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content.features[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<Simplify<ContentDocumentDataFeaturesItem>>;
}

/**
 * Content document from Prismic
 *
 * - **API ID**: `content`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContentDocumentData>,
    "content",
    Lang
  >;

type CtaEmailDocumentDataSlicesSlice = CallToActionSlice;

/**
 * Content for CTA documents
 */
interface CtaEmailDocumentData {
  /**
   * Url field in *CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_email.url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url: prismic.KeyTextField;

  /**
   * Button Label field in *CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_email.button_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Placeholder field in *CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_email.placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Slice Zone field in *CTA*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_email.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CtaEmailDocumentDataSlicesSlice>;
}

/**
 * CTA document from Prismic
 *
 * - **API ID**: `cta_email`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CtaEmailDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CtaEmailDocumentData>,
    "cta_email",
    Lang
  >;

/**
 * Content for Customer Review documents
 */
interface CustomerReviewDocumentData {
  /**
   * Review field in *Customer Review*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_review.review
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  review: prismic.KeyTextField;

  /**
   * Rating field in *Customer Review*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_review.rating
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  rating: prismic.NumberField;

  /**
   * Creator field in *Customer Review*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_review.creator
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  creator: prismic.KeyTextField;

  /**
   * Arrow Pointing field in *Customer Review*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_review.arrow_pointing
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  arrow_pointing: prismic.KeyTextField;
}

/**
 * Customer Review document from Prismic
 *
 * - **API ID**: `customer_review`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CustomerReviewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CustomerReviewDocumentData>,
    "customer_review",
    Lang
  >;

/**
 * Item in *Footer Navigation → navs*
 */
export interface FooterNavigationDocumentDataNavsItem {
  /**
   * nav field in *Footer Navigation → navs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.navs[].nav
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nav: prismic.ContentRelationshipField;
}

/**
 * Content for Footer Navigation documents
 */
interface FooterNavigationDocumentData {
  /**
   * navs field in *Footer Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.navs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navs: prismic.GroupField<Simplify<FooterNavigationDocumentDataNavsItem>>;
}

/**
 * Footer Navigation document from Prismic
 *
 * - **API ID**: `footer_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FooterNavigationDocumentData>,
    "footer_navigation",
    Lang
  >;

/**
 * Item in *HeaderNavigation → Navs*
 */
export interface HeaderDocumentDataNavsItem {
  /**
   * Nav field in *HeaderNavigation → Navs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navs[].nav
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nav: prismic.ContentRelationshipField;
}

type HeaderDocumentDataSlicesSlice = HeaderSlice;

/**
 * Content for HeaderNavigation documents
 */
interface HeaderDocumentData {
  /**
   * Navs field in *HeaderNavigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navs: prismic.GroupField<Simplify<HeaderDocumentDataNavsItem>>;

  /**
   * type field in *HeaderNavigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  type: prismic.KeyTextField;

  /**
   * Slice Zone field in *HeaderNavigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice> /**
   * object_ids field in *HeaderNavigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.object_ids
   * - **Tab**: square
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  object_ids: prismic.KeyTextField;
}

/**
 * HeaderNavigation document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HeaderDocumentData>, "header", Lang>;

type HomepageDocumentDataSlicesSlice =
  | SlidersSlice
  | WindowPanelsSlice
  | FeaturedCategoriesSlice
  | Hero2Slice
  | HeroSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for Social Media Handle documents
 */
interface SocialMediaHandleDocumentData {
  /**
   * Social Media Name field in *Social Media Handle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_handle.social_media_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  social_media_name: prismic.KeyTextField;

  /**
   * Social Media Url field in *Social Media Handle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_handle.social_media_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  social_media_url: prismic.KeyTextField;

  /**
   * Social Media Logo field in *Social Media Handle*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_handle.social_media_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_media_logo: prismic.ImageField<never>;
}

/**
 * Social Media Handle document from Prismic
 *
 * - **API ID**: `social_media_handle`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialMediaHandleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SocialMediaHandleDocumentData>,
    "social_media_handle",
    Lang
  >;

type SocialMediaLinksDocumentDataSlicesSlice = SocialMediaLinksSlice;

/**
 * Content for Social Media Handles documents
 */
interface SocialMediaLinksDocumentData {
  /**
   * Slice Zone field in *Social Media Handles*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_links.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SocialMediaLinksDocumentDataSlicesSlice>;
}

/**
 * Social Media Handles document from Prismic
 *
 * - **API ID**: `social_media_links`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialMediaLinksDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SocialMediaLinksDocumentData>,
    "social_media_links",
    Lang
  >;

/**
 * Content for The Playground Display Logo documents
 */
interface ThePlaygroundDisplayLogoDocumentData {
  /**
   * image field in *The Playground Display Logo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: the_playground_display_logo.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * The Playground Display Logo document from Prismic
 *
 * - **API ID**: `the_playground_display_logo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ThePlaygroundDisplayLogoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ThePlaygroundDisplayLogoDocumentData>,
    "the_playground_display_logo",
    Lang
  >;

export type AllDocumentTypes =
  | BlogPostDocument
  | CategorylinkDocument
  | ComingSoonDocument
  | ContentDocument
  | CtaEmailDocument
  | CustomerReviewDocument
  | FooterNavigationDocument
  | HeaderDocument
  | HomepageDocument
  | SocialMediaHandleDocument
  | SocialMediaLinksDocument
  | ThePlaygroundDisplayLogoDocument;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Call Description field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.call_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_description: prismic.KeyTextField;

  /**
   * Action Button Text field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.action_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  action_button_text: prismic.KeyTextField;

  /**
   * Form Placeholder Text field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.form_placeholder_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_placeholder_text: prismic.KeyTextField;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CallToAction → OnlyButton → Primary*
 */
export interface CallToActionSliceOnlyButtonPrimary {
  /**
   * Action Button Text field in *CallToAction → OnlyButton → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.onlyButton.primary.action_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  action_button_text: prismic.KeyTextField;
}

/**
 * OnlyButton variation for CallToAction Slice
 *
 * - **API ID**: `onlyButton`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceOnlyButton = prismic.SharedSliceVariation<
  "onlyButton",
  Simplify<CallToActionSliceOnlyButtonPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation =
  | CallToActionSliceDefault
  | CallToActionSliceOnlyButton;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *CallToAction2 → Default → Primary*
 */
export interface CallToAction2SliceDefaultPrimary {
  /**
   * Image field in *CallToAction2 → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_2.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *CallToAction2 → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_2.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * paragraph field in *CallToAction2 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_2.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * buttonLink field in *CallToAction2 → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Redirect URL for CTA button
   * - **API ID Path**: call_to_action_2.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * buttonLabel field in *CallToAction2 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Label for CTA button
   * - **API ID Path**: call_to_action_2.default.primary.buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField;
}

/**
 * Default variation for CallToAction2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToAction2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToAction2SliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CallToAction2 → AlignLeft → Primary*
 */
export interface CallToAction2SliceAlignLeftPrimary {
  /**
   * Image field in *CallToAction2 → AlignLeft → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_2.alignLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *CallToAction2 → AlignLeft → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_2.alignLeft.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * paragraph field in *CallToAction2 → AlignLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_2.alignLeft.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * buttonLink field in *CallToAction2 → AlignLeft → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Redirect URL for CTA button
   * - **API ID Path**: call_to_action_2.alignLeft.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * buttonLabel field in *CallToAction2 → AlignLeft → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Label for CTA button
   * - **API ID Path**: call_to_action_2.alignLeft.primary.buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField;
}

/**
 * AlignLeft variation for CallToAction2 Slice
 *
 * - **API ID**: `alignLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToAction2SliceAlignLeft = prismic.SharedSliceVariation<
  "alignLeft",
  Simplify<CallToAction2SliceAlignLeftPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction2*
 */
type CallToAction2SliceVariation =
  | CallToAction2SliceDefault
  | CallToAction2SliceAlignLeft;

/**
 * CallToAction2 Shared Slice
 *
 * - **API ID**: `call_to_action_2`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToAction2Slice = prismic.SharedSlice<
  "call_to_action_2",
  CallToAction2SliceVariation
>;

/**
 * Primary content in *FeaturedCategories → Items*
 */
export interface FeaturedCategoriesSliceDefaultItem {
  /**
   * Category field in *FeaturedCategories → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_categories.items[].category
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField;
}

/**
 * Default variation for FeaturedCategories Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedCategoriesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<FeaturedCategoriesSliceDefaultItem>
>;

/**
 * Slice variation for *FeaturedCategories*
 */
type FeaturedCategoriesSliceVariation = FeaturedCategoriesSliceDefault;

/**
 * FeaturedCategories Shared Slice
 *
 * - **API ID**: `featured_categories`
 * - **Description**: FeaturedCategories
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedCategoriesSlice = prismic.SharedSlice<
  "featured_categories",
  FeaturedCategoriesSliceVariation
>;

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * background image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.bg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_image: prismic.ImageField<"mobile">;

  /**
   * content alignment field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.content_alignment
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content_alignment: prismic.KeyTextField;

  /**
   * font size field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.font_size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  font_size: prismic.KeyTextField;

  /**
   * text content position field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.text_content_position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_content_position: prismic.KeyTextField;

  /**
   * fluid field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.fluid
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  fluid: prismic.BooleanField;

  /**
   * link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;

  /**
   * social media handles field in *Hero → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.social_media_handles
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_media_handles: prismic.ContentRelationshipField<"social_media_links">;

  /**
   * cta field in *Hero → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.ContentRelationshipField<"cta_email">;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Carousel → Primary*
 */
export interface HeroSliceCarouselPrimary {
  /**
   * title field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * content alignment field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.content_alignment
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content_alignment: prismic.KeyTextField;

  /**
   * cta field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.ContentRelationshipField<"cta_email">;

  /**
   * font_size field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.font_size
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  font_size: prismic.KeyTextField;

  /**
   * text content position field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.text_content_position
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_content_position: prismic.KeyTextField;

  /**
   * color field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  color: prismic.ColorField;

  /**
   * fluid field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.carousel.primary.fluid
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  fluid: prismic.BooleanField;

  /**
   * social media handles field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.social_media_handles
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_media_handles: prismic.ContentRelationshipField<"social_media_links">;

  /**
   * link field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceCarouselItem {
  /**
   * background image field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].bg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  bg_image: prismic.ImageField<"mobile">;
}

/**
 * Carousel variation for Hero Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceCarousel = prismic.SharedSliceVariation<
  "carousel",
  Simplify<HeroSliceCarouselPrimary>,
  Simplify<HeroSliceCarouselItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceCarousel;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ProductShowcase → Default → Primary*
 */
export interface Hero2SliceDefaultPrimary {
  /**
   * headline field in *ProductShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero_2.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * description field in *ProductShowcase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *ProductShowcase → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description Align field in *ProductShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.description_align
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description_align: prismic.KeyTextField;

  /**
   * window field in *ProductShowcase → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_2.default.primary.window
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  window: prismic.BooleanField;

  /**
   * Call To Action Link field in *ProductShowcase → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.call_to_action_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  call_to_action_link: prismic.ContentRelationshipField;

  /**
   * Call To Action Label field in *ProductShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.call_to_action_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_to_action_label: prismic.KeyTextField;

  /**
   * title field in *ProductShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for ProductShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Hero2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductShowcase*
 */
type Hero2SliceVariation = Hero2SliceDefault;

/**
 * ProductShowcase Shared Slice
 *
 * - **API ID**: `hero_2`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero2Slice = prismic.SharedSlice<"hero_2", Hero2SliceVariation>;

/**
 * Primary content in *Newsletter → Default → Primary*
 */
export interface NewsletterSliceDefaultPrimary {
  /**
   * title field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * cta button text field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.cta_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_button_text: prismic.KeyTextField;
}

/**
 * Default variation for Newsletter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsletterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Newsletter*
 */
type NewsletterSliceVariation = NewsletterSliceDefault;

/**
 * Newsletter Shared Slice
 *
 * - **API ID**: `newsletter`
 * - **Description**: Newsletter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSlice = prismic.SharedSlice<
  "newsletter",
  NewsletterSliceVariation
>;

/**
 * Item in *Sliders → blog → Primary → blogs*
 */
export interface SlidersSliceBlogPrimaryItemsItem {
  /**
   * blog field in *Sliders → blog → Primary → blogs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.blog.primary.items[].blog
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  blog: prismic.ContentRelationshipField<"blog">;
}

/**
 * Item in *Sliders → icon → Primary → icons*
 */
export interface SlidersSliceIconsPrimaryIconsItem {
  /**
   * image field in *Sliders → icon → Primary → icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.icons.primary.icons[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * image description field in *Sliders → icon → Primary → icons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.icons.primary.icons[].image_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_description: prismic.KeyTextField;
}

/**
 * Primary content in *Sliders → product → Primary*
 */
export interface SlidersSliceDefaultPrimary {
  /**
   * Slider Title field in *Sliders → product → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: sliders.default.primary.slider_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slider_title: prismic.KeyTextField;

  /**
   * Object IDs field in *Sliders → product → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: id
   * - **API ID Path**: sliders.default.primary.object_ids
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  object_ids: prismic.KeyTextField;

  /**
   * sliderHeadline field in *Sliders → product → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.default.primary.sliderheadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sliderheadline: prismic.KeyTextField;

  /**
   * imageFit field in *Sliders → product → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: contain
   * - **API ID Path**: sliders.default.primary.imagefit
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  imagefit: prismic.SelectField<"contain" | "cover", "filled">;
}

/**
 * product variation for Sliders Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlidersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SlidersSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Sliders → blog → Primary*
 */
export interface SlidersSliceBlogPrimary {
  /**
   * Slider Title field in *Sliders → blog → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: sliders.blog.primary.slider_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slider_title: prismic.KeyTextField;

  /**
   * sliderHeadline field in *Sliders → blog → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.blog.primary.sliderheadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sliderheadline: prismic.KeyTextField;

  /**
   * blogs field in *Sliders → blog → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.blog.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<SlidersSliceBlogPrimaryItemsItem>>;

  /**
   * imageFit field in *Sliders → blog → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: contain
   * - **API ID Path**: sliders.blog.primary.imagefit
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  imagefit: prismic.SelectField<"contain" | "cover", "filled">;
}

/**
 * blog variation for Sliders Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlidersSliceBlog = prismic.SharedSliceVariation<
  "blog",
  Simplify<SlidersSliceBlogPrimary>,
  never
>;

/**
 * Primary content in *Sliders → icon → Primary*
 */
export interface SlidersSliceIconsPrimary {
  /**
   * Slider Title field in *Sliders → icon → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: sliders.icons.primary.slider_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slider_title: prismic.KeyTextField;

  /**
   * sliderHeadline field in *Sliders → icon → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.icons.primary.sliderheadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sliderheadline: prismic.KeyTextField;

  /**
   * imageFit field in *Sliders → icon → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: contain
   * - **API ID Path**: sliders.icons.primary.imagefit
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  imagefit: prismic.SelectField<"contain" | "cover", "filled">;

  /**
   * icons field in *Sliders → icon → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.icons.primary.icons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  icons: prismic.GroupField<Simplify<SlidersSliceIconsPrimaryIconsItem>>;
}

/**
 * icon variation for Sliders Slice
 *
 * - **API ID**: `icons`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlidersSliceIcons = prismic.SharedSliceVariation<
  "icons",
  Simplify<SlidersSliceIconsPrimary>,
  never
>;

/**
 * Slice variation for *Sliders*
 */
type SlidersSliceVariation =
  | SlidersSliceDefault
  | SlidersSliceBlog
  | SlidersSliceIcons;

/**
 * Sliders Shared Slice
 *
 * - **API ID**: `sliders`
 * - **Description**: Sliders
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlidersSlice = prismic.SharedSlice<
  "sliders",
  SlidersSliceVariation
>;

/**
 * Primary content in *SocialMediaLinks → Items*
 */
export interface SocialMediaLinksSliceDefaultItem {
  /**
   * Social Media Handle field in *SocialMediaLinks → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_links.items[].social_media_handle
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_media_handle: prismic.LinkField;
}

/**
 * Default variation for SocialMediaLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialMediaLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SocialMediaLinksSliceDefaultItem>
>;

/**
 * Slice variation for *SocialMediaLinks*
 */
type SocialMediaLinksSliceVariation = SocialMediaLinksSliceDefault;

/**
 * SocialMediaLinks Shared Slice
 *
 * - **API ID**: `social_media_links`
 * - **Description**: SocialMediaLinks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialMediaLinksSlice = prismic.SharedSlice<
  "social_media_links",
  SocialMediaLinksSliceVariation
>;

/**
 * Primary content in *WindowPanels → Items*
 */
export interface WindowPanelsSliceDefaultItem {
  /**
   * Window BG field in *WindowPanels → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: window_panels.items[].window_bg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  window_bg: prismic.ImageField<never>;

  /**
   * Review field in *WindowPanels → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: window_panels.items[].review
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  review: prismic.ContentRelationshipField;
}

/**
 * Default variation for WindowPanels Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WindowPanelsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<WindowPanelsSliceDefaultItem>
>;

/**
 * Primary content in *WindowPanels → doubled-up → Primary*
 */
export interface WindowPanelsSliceDoubledUpPrimary {
  /**
   * Double Up WIndow field in *WindowPanels → doubled-up → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: window_panels.doubledUp.primary.double_up_window
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  double_up_window: prismic.NumberField;
}

/**
 * Primary content in *WindowPanels → Items*
 */
export interface WindowPanelsSliceDoubledUpItem {
  /**
   * Window BG field in *WindowPanels → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: window_panels.items[].window_bg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  window_bg: prismic.ImageField<never>;

  /**
   * Review field in *WindowPanels → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: window_panels.items[].review
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  review: prismic.ContentRelationshipField;
}

/**
 * doubled-up variation for WindowPanels Slice
 *
 * - **API ID**: `doubledUp`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WindowPanelsSliceDoubledUp = prismic.SharedSliceVariation<
  "doubledUp",
  Simplify<WindowPanelsSliceDoubledUpPrimary>,
  Simplify<WindowPanelsSliceDoubledUpItem>
>;

/**
 * Slice variation for *WindowPanels*
 */
type WindowPanelsSliceVariation =
  | WindowPanelsSliceDefault
  | WindowPanelsSliceDoubledUp;

/**
 * WindowPanels Shared Slice
 *
 * - **API ID**: `window_panels`
 * - **Description**: WindowPanels
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WindowPanelsSlice = prismic.SharedSlice<
  "window_panels",
  WindowPanelsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      BlogPostDocumentDataSectionsItem,
      CategorylinkDocument,
      CategorylinkDocumentData,
      ComingSoonDocument,
      ComingSoonDocumentData,
      ComingSoonDocumentDataSlicesSlice,
      ContentDocument,
      ContentDocumentData,
      ContentDocumentDataFeaturesItem,
      CtaEmailDocument,
      CtaEmailDocumentData,
      CtaEmailDocumentDataSlicesSlice,
      CustomerReviewDocument,
      CustomerReviewDocumentData,
      FooterNavigationDocument,
      FooterNavigationDocumentData,
      FooterNavigationDocumentDataNavsItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavsItem,
      HeaderDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      SocialMediaHandleDocument,
      SocialMediaHandleDocumentData,
      SocialMediaLinksDocument,
      SocialMediaLinksDocumentData,
      SocialMediaLinksDocumentDataSlicesSlice,
      ThePlaygroundDisplayLogoDocument,
      ThePlaygroundDisplayLogoDocumentData,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceOnlyButtonPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CallToActionSliceOnlyButton,
      CallToAction2Slice,
      CallToAction2SliceDefaultPrimary,
      CallToAction2SliceAlignLeftPrimary,
      CallToAction2SliceVariation,
      CallToAction2SliceDefault,
      CallToAction2SliceAlignLeft,
      FeaturedCategoriesSlice,
      FeaturedCategoriesSliceDefaultItem,
      FeaturedCategoriesSliceVariation,
      FeaturedCategoriesSliceDefault,
      HeaderSlice,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceCarouselPrimary,
      HeroSliceCarouselItem,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceCarousel,
      Hero2Slice,
      Hero2SliceDefaultPrimary,
      Hero2SliceVariation,
      Hero2SliceDefault,
      NewsletterSlice,
      NewsletterSliceDefaultPrimary,
      NewsletterSliceVariation,
      NewsletterSliceDefault,
      SlidersSlice,
      SlidersSliceDefaultPrimary,
      SlidersSliceBlogPrimaryItemsItem,
      SlidersSliceBlogPrimary,
      SlidersSliceIconsPrimaryIconsItem,
      SlidersSliceIconsPrimary,
      SlidersSliceVariation,
      SlidersSliceDefault,
      SlidersSliceBlog,
      SlidersSliceIcons,
      SocialMediaLinksSlice,
      SocialMediaLinksSliceDefaultItem,
      SocialMediaLinksSliceVariation,
      SocialMediaLinksSliceDefault,
      WindowPanelsSlice,
      WindowPanelsSliceDefaultItem,
      WindowPanelsSliceDoubledUpPrimary,
      WindowPanelsSliceDoubledUpItem,
      WindowPanelsSliceVariation,
      WindowPanelsSliceDefault,
      WindowPanelsSliceDoubledUp,
    };
  }
}
