// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BlogPostDocumentDataSlicesSlice = HeroSlice;

/**
 * Item in *Blog Post → sections*
 */
export interface BlogPostDocumentDataSectionsItem {
  /**
   * heading field in *Blog Post → sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sections[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * paragraph field in *Blog Post → sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sections[].paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;

  /**
   * image field in *Blog Post → sections*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sections[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * table field in *Blog Post → sections*
   *
   * - **Field Type**: Table
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sections[].table
   * - **Documentation**: https://prismic.io/docs/fields/table
   */
  table: prismic.TableField;

  /**
   * includeDividers field in *Blog Post → sections*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: blog_post.sections[].includeDividers
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  includeDividers: prismic.BooleanField;

  /**
   * video field in *Blog Post → sections*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sections[].video
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video: prismic.EmbedField;

  /**
   * blockquote field in *Blog Post → sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sections[].blockquote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  blockquote: prismic.RichTextField;
}

type BlogPostDocumentDataSlices2Slice =
  | VideoSlice
  | BlockQuoteSlice
  | ImageSlice
  | BlogTextSlice;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Catch Hook
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * headline field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.headline
   * - **Tab**: Catch Hook
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.image
   * - **Tab**: Catch Hook
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Catch Hook
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice>; /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>; /**
   * sections field in *Blog Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.sections[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  sections: prismic.GroupField<Simplify<BlogPostDocumentDataSectionsItem>>;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices2[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices2: prismic.SliceZone<BlogPostDocumentDataSlices2Slice>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

/**
 * Content for CategoryLink documents
 */
interface CategorylinkDocumentData {
  /**
   * Title field in *CategoryLink*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categorylink.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *CategoryLink*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categorylink.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *CategoryLink*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categorylink.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link: prismic.KeyTextField;
}

/**
 * CategoryLink document from Prismic
 *
 * - **API ID**: `categorylink`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategorylinkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategorylinkDocumentData>,
    "categorylink",
    Lang
  >;

type ComingSoonDocumentDataSlicesSlice = SocialMediaLinksSlice | HeroSlice;

/**
 * Content for Coming Soon documents
 */
interface ComingSoonDocumentData {
  /**
   * image field in *Coming Soon*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coming_soon.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Coming Soon*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: coming_soon.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ComingSoonDocumentDataSlicesSlice>; /**
   * Meta Description field in *Coming Soon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: coming_soon.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Coming Soon*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coming_soon.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Coming Soon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: coming_soon.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Coming Soon document from Prismic
 *
 * - **API ID**: `coming_soon`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ComingSoonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ComingSoonDocumentData>,
    "coming_soon",
    Lang
  >;

/**
 * Item in *Content → features*
 */
export interface ContentDocumentDataFeaturesItem {
  /**
   * image field in *Content → features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.features[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Content → features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.features[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Content → features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.features[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * headline field in *Content → features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.features[].headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;
}

/**
 * Content for Content documents
 */
interface ContentDocumentData {
  /**
   * features field in *Content*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content.features[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<Simplify<ContentDocumentDataFeaturesItem>>;
}

/**
 * Content document from Prismic
 *
 * - **API ID**: `content`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContentDocumentData>,
    "content",
    Lang
  >;

type CtaEmailDocumentDataSlicesSlice = never;

/**
 * Content for CTA documents
 */
interface CtaEmailDocumentData {
  /**
   * Url field in *CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_email.url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  url: prismic.KeyTextField;

  /**
   * Button Label field in *CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_email.button_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField;

  /**
   * Placeholder field in *CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_email.placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder: prismic.KeyTextField;

  /**
   * Slice Zone field in *CTA*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_email.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<CtaEmailDocumentDataSlicesSlice>;
}

/**
 * CTA document from Prismic
 *
 * - **API ID**: `cta_email`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CtaEmailDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CtaEmailDocumentData>,
    "cta_email",
    Lang
  >;

/**
 * Content for Customer Review documents
 */
interface CustomerReviewDocumentData {
  /**
   * Review field in *Customer Review*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_review.review
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  review: prismic.KeyTextField;

  /**
   * Rating field in *Customer Review*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_review.rating
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rating: prismic.NumberField;

  /**
   * Creator field in *Customer Review*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_review.creator
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  creator: prismic.KeyTextField;

  /**
   * Arrow Pointing field in *Customer Review*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_review.arrow_pointing
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  arrow_pointing: prismic.KeyTextField;
}

/**
 * Customer Review document from Prismic
 *
 * - **API ID**: `customer_review`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CustomerReviewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CustomerReviewDocumentData>,
    "customer_review",
    Lang
  >;

/**
 * Item in *Footer Navigation → navs*
 */
export interface FooterNavigationDocumentDataNavsItem {
  /**
   * nav field in *Footer Navigation → navs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.navs[].nav
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  nav: prismic.ContentRelationshipField;
}

/**
 * Content for Footer Navigation documents
 */
interface FooterNavigationDocumentData {
  /**
   * navs field in *Footer Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_navigation.navs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navs: prismic.GroupField<Simplify<FooterNavigationDocumentDataNavsItem>>;
}

/**
 * Footer Navigation document from Prismic
 *
 * - **API ID**: `footer_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<FooterNavigationDocumentData>,
    "footer_navigation",
    Lang
  >;

/**
 * Item in *HeaderNavigation → Navs*
 */
export interface HeaderDocumentDataNavsItem {
  /**
   * Nav field in *HeaderNavigation → Navs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navs[].nav
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  nav: prismic.ContentRelationshipField;
}

type HeaderDocumentDataSlicesSlice = HeaderSlice;

/**
 * Content for HeaderNavigation documents
 */
interface HeaderDocumentData {
  /**
   * Navs field in *HeaderNavigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navs: prismic.GroupField<Simplify<HeaderDocumentDataNavsItem>>;

  /**
   * type field in *HeaderNavigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  type: prismic.KeyTextField;

  /**
   * Slice Zone field in *HeaderNavigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>; /**
   * object_ids field in *HeaderNavigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.object_ids
   * - **Tab**: square
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  object_ids: prismic.KeyTextField;
}

/**
 * HeaderNavigation document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HeaderDocumentData>, "header", Lang>;

type HomepageDocumentDataSlicesSlice =
  | SlidersSlice
  | WindowPanelsSlice
  | FeaturedCategoriesSlice
  | Hero2Slice
  | HeroSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Product Content → Features *
 */
export interface ProductContentDocumentDataFeaturesItem {
  /**
   * Info Name field in *Product Content → Features *
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_content.features[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Info Value field in *Product Content → Features *
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_content.features[].value
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  value: prismic.RichTextField;
}

/**
 * Item in *Product Content → Feature Showcases*
 */
export interface ProductContentDocumentDataShowcasesItem {
  /**
   * Image field in *Product Content → Feature Showcases*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_content.showcases[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Product Content → Feature Showcases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_content.showcases[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Product Content → Feature Showcases*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_content.showcases[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Video Playback ID field in *Product Content → Feature Showcases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_content.showcases[].video_playback_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  video_playback_id: prismic.KeyTextField;
}

/**
 * Content for Product Content documents
 */
interface ProductContentDocumentData {
  /**
   * Product ID field in *Product Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_content.product_id
   * - **Tab**: Info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  product_id: prismic.KeyTextField;

  /**
   * Features  field in *Product Content*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product_content.features[]
   * - **Tab**: Info
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<
    Simplify<ProductContentDocumentDataFeaturesItem>
  >;

  /**
   * Feature Showcases field in *Product Content*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product_content.showcases[]
   * - **Tab**: Info
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  showcases: prismic.GroupField<
    Simplify<ProductContentDocumentDataShowcasesItem>
  >;

  /**
   * Full Width Image field in *Product Content*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_content.image
   * - **Tab**: Info
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Product Content document from Prismic
 *
 * - **API ID**: `product_content`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductContentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductContentDocumentData>,
    "product_content",
    Lang
  >;

/**
 * Item in *Product Landing Page → quick points*
 */
export interface ProductLandingPageDocumentDataQuickPointsItem {
  /**
   * point field in *Product Landing Page → quick points*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_landing_page.quick_points[].point
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  point: prismic.KeyTextField;
}

type ProductLandingPageDocumentDataSlicesSlice =
  | TestimonialGallerySlice
  | FaqAccordionSlice
  | BenefitsCalloutSlice
  | DropListSlice
  | Hero2Slice
  | HeroSlice;

/**
 * Content for Product Landing Page documents
 */
interface ProductLandingPageDocumentData {
  /**
   * quick points field in *Product Landing Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product_landing_page.quick_points[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  quick_points: prismic.GroupField<
    Simplify<ProductLandingPageDocumentDataQuickPointsItem>
  >;

  /**
   * title field in *Product Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_landing_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Product Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_landing_page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * product id field in *Product Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_landing_page.product_id
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  product_id: prismic.KeyTextField;

  /**
   * Slice Zone field in *Product Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product_landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProductLandingPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Product Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: product_landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Product Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: product_landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Product Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Product Landing Page document from Prismic
 *
 * - **API ID**: `product_landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductLandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductLandingPageDocumentData>,
    "product_landing_page",
    Lang
  >;

/**
 * Content for Social Media Handle documents
 */
interface SocialMediaHandleDocumentData {
  /**
   * Social Media Name field in *Social Media Handle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_handle.social_media_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  social_media_name: prismic.KeyTextField;

  /**
   * Social Media Url field in *Social Media Handle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_handle.social_media_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  social_media_url: prismic.KeyTextField;

  /**
   * Social Media Logo field in *Social Media Handle*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_handle.social_media_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  social_media_logo: prismic.ImageField<never>;
}

/**
 * Social Media Handle document from Prismic
 *
 * - **API ID**: `social_media_handle`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialMediaHandleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SocialMediaHandleDocumentData>,
    "social_media_handle",
    Lang
  >;

type SocialMediaLinksDocumentDataSlicesSlice = SocialMediaLinksSlice;

/**
 * Content for Social Media Handles documents
 */
interface SocialMediaLinksDocumentData {
  /**
   * Slice Zone field in *Social Media Handles*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_links.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SocialMediaLinksDocumentDataSlicesSlice>;
}

/**
 * Social Media Handles document from Prismic
 *
 * - **API ID**: `social_media_links`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialMediaLinksDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SocialMediaLinksDocumentData>,
    "social_media_links",
    Lang
  >;

/**
 * Content for The Playground Display Logo documents
 */
interface ThePlaygroundDisplayLogoDocumentData {
  /**
   * image field in *The Playground Display Logo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: the_playground_display_logo.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * The Playground Display Logo document from Prismic
 *
 * - **API ID**: `the_playground_display_logo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ThePlaygroundDisplayLogoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ThePlaygroundDisplayLogoDocumentData>,
    "the_playground_display_logo",
    Lang
  >;

export type AllDocumentTypes =
  | BlogPostDocument
  | CategorylinkDocument
  | ComingSoonDocument
  | ContentDocument
  | CtaEmailDocument
  | CustomerReviewDocument
  | FooterNavigationDocument
  | HeaderDocument
  | HomepageDocument
  | ProductContentDocument
  | ProductLandingPageDocument
  | SocialMediaHandleDocument
  | SocialMediaLinksDocument
  | ThePlaygroundDisplayLogoDocument;

/**
 * Item in *BenefitsCallout → Default → Primary → Benefits*
 */
export interface BenefitsCalloutSliceDefaultPrimaryBenefitsItem {
  /**
   * Benefit Text field in *BenefitsCallout → Default → Primary → Benefits*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits_callout.default.primary.benefits[].benefit_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  benefit_text: prismic.RichTextField;
}

/**
 * Primary content in *BenefitsCallout → Default → Primary*
 */
export interface BenefitsCalloutSliceDefaultPrimary {
  /**
   * Headline field in *BenefitsCallout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits_callout.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Subheading field in *BenefitsCallout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits_callout.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subheading: prismic.RichTextField;

  /**
   * Benefits field in *BenefitsCallout → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits_callout.default.primary.benefits[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  benefits: prismic.GroupField<
    Simplify<BenefitsCalloutSliceDefaultPrimaryBenefitsItem>
  >;
}

/**
 * Default variation for BenefitsCallout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BenefitsCalloutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BenefitsCalloutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BenefitsCallout*
 */
type BenefitsCalloutSliceVariation = BenefitsCalloutSliceDefault;

/**
 * BenefitsCallout Shared Slice
 *
 * - **API ID**: `benefits_callout`
 * - **Description**: A callout section with urgency headline, subheading, and a list of benefits with checkmarks
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BenefitsCalloutSlice = prismic.SharedSlice<
  "benefits_callout",
  BenefitsCalloutSliceVariation
>;

/**
 * Default variation for BlockQuote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlockQuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BlockQuote*
 */
type BlockQuoteSliceVariation = BlockQuoteSliceDefault;

/**
 * BlockQuote Shared Slice
 *
 * - **API ID**: `block_quote`
 * - **Description**: BlockQuote
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlockQuoteSlice = prismic.SharedSlice<
  "block_quote",
  BlockQuoteSliceVariation
>;

/**
 * Default variation for BlogText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BlogText*
 */
type BlogTextSliceVariation = BlogTextSliceDefault;

/**
 * BlogText Shared Slice
 *
 * - **API ID**: `blog_text`
 * - **Description**: BlogText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogTextSlice = prismic.SharedSlice<
  "blog_text",
  BlogTextSliceVariation
>;

/**
 * Item in *DropList → Default → Primary → DropItems*
 */
export interface DropListSliceDefaultPrimaryDropitemsItem {
  /**
   * title field in *DropList → Default → Primary → DropItems*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drop_list.default.primary.dropitems[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *DropList → Default → Primary → DropItems*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drop_list.default.primary.dropitems[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *DropList → Default → Primary*
 */
export interface DropListSliceDefaultPrimary {
  /**
   * image field in *DropList → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: drop_list.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *DropList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drop_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * headline field in *DropList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drop_list.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * DropItems field in *DropList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: drop_list.default.primary.dropitems[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  dropitems: prismic.GroupField<
    Simplify<DropListSliceDefaultPrimaryDropitemsItem>
  >;

  /**
   * description field in *DropList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drop_list.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for DropList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DropListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DropListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DropList*
 */
type DropListSliceVariation = DropListSliceDefault;

/**
 * DropList Shared Slice
 *
 * - **API ID**: `drop_list`
 * - **Description**: DropList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DropListSlice = prismic.SharedSlice<
  "drop_list",
  DropListSliceVariation
>;

/**
 * Item in *FaqAccordion → Default → Primary → Questions*
 */
export interface FaqAccordionSliceDefaultPrimaryFaqItemsItem {
  /**
   * Question field in *FaqAccordion → Default → Primary → Questions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_accordion.default.primary.faq_items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FaqAccordion → Default → Primary → Questions*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_accordion.default.primary.faq_items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *FaqAccordion → Default → Primary*
 */
export interface FaqAccordionSliceDefaultPrimary {
  /**
   * Section Title field in *FaqAccordion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_accordion.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Section Intro field in *FaqAccordion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_accordion.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Questions field in *FaqAccordion → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_accordion.default.primary.faq_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faq_items: prismic.GroupField<
    Simplify<FaqAccordionSliceDefaultPrimaryFaqItemsItem>
  >;
}

/**
 * Default variation for FaqAccordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard FAQ accordion with a section title, description, and collapsible items for each question and answer.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqAccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqAccordionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FaqAccordion*
 */
type FaqAccordionSliceVariation = FaqAccordionSliceDefault;

/**
 * FaqAccordion Shared Slice
 *
 * - **API ID**: `faq_accordion`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqAccordionSlice = prismic.SharedSlice<
  "faq_accordion",
  FaqAccordionSliceVariation
>;

/**
 * Primary content in *FeaturedCategories → Items*
 */
export interface FeaturedCategoriesSliceDefaultItem {
  /**
   * Category field in *FeaturedCategories → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_categories.items[].category
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  category: prismic.ContentRelationshipField;
}

/**
 * Default variation for FeaturedCategories Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedCategoriesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<FeaturedCategoriesSliceDefaultItem>
>;

/**
 * Slice variation for *FeaturedCategories*
 */
type FeaturedCategoriesSliceVariation = FeaturedCategoriesSliceDefault;

/**
 * FeaturedCategories Shared Slice
 *
 * - **API ID**: `featured_categories`
 * - **Description**: FeaturedCategories
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedCategoriesSlice = prismic.SharedSlice<
  "featured_categories",
  FeaturedCategoriesSliceVariation
>;

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * background image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.bg_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bg_image: prismic.ImageField<"mobile">;

  /**
   * content alignment field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.content_alignment
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  content_alignment: prismic.KeyTextField;

  /**
   * font size field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.font_size
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  font_size: prismic.KeyTextField;

  /**
   * text content position field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.text_content_position
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text_content_position: prismic.KeyTextField;

  /**
   * fluid field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.fluid
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  fluid: prismic.BooleanField;

  /**
   * link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link: prismic.KeyTextField;

  /**
   * social media handles field in *Hero → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.social_media_handles
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  social_media_handles: prismic.ContentRelationshipField<"social_media_links">;

  /**
   * cta field in *Hero → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  cta: prismic.ContentRelationshipField<"cta_email">;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Carousel → Primary*
 */
export interface HeroSliceCarouselPrimary {
  /**
   * title field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * content alignment field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.content_alignment
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  content_alignment: prismic.KeyTextField;

  /**
   * cta field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  cta: prismic.ContentRelationshipField<"cta_email">;

  /**
   * font_size field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.font_size
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  font_size: prismic.KeyTextField;

  /**
   * text content position field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.text_content_position
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text_content_position: prismic.KeyTextField;

  /**
   * color field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  color: prismic.ColorField;

  /**
   * fluid field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.carousel.primary.fluid
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  fluid: prismic.BooleanField;

  /**
   * social media handles field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.social_media_handles
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  social_media_handles: prismic.ContentRelationshipField<"social_media_links">;

  /**
   * link field in *Hero → Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.carousel.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceCarouselItem {
  /**
   * background image field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].bg_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bg_image: prismic.ImageField<"mobile">;
}

/**
 * Carousel variation for Hero Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceCarousel = prismic.SharedSliceVariation<
  "carousel",
  Simplify<HeroSliceCarouselPrimary>,
  Simplify<HeroSliceCarouselItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceCarousel;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *ProductShowcase → 1 → Primary → cards*
 */
export interface Hero2SliceDefaultPrimaryCardsItem {
  /**
   * image field in *ProductShowcase → 1 → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *ProductShowcase → 1 → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * headline field in *ProductShowcase → 1 → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.cards[].headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * description field in *ProductShowcase → 1 → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * type field in *ProductShowcase → 1 → Primary → cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: image
   * - **API ID Path**: hero_2.default.primary.cards[].type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<"image" | "review" | "step", "filled">;
}

/**
 * Item in *ProductShowcase → 2 → Primary → cards*
 */
export interface Hero2SliceStyle2PrimaryCardsItem {
  /**
   * image field in *ProductShowcase → 2 → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style2.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *ProductShowcase → 2 → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style2.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * headline field in *ProductShowcase → 2 → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style2.primary.cards[].headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * description field in *ProductShowcase → 2 → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style2.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * type field in *ProductShowcase → 2 → Primary → cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: image
   * - **API ID Path**: hero_2.style2.primary.cards[].type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<"image" | "review" | "step", "filled">;
}

/**
 * Item in *ProductShowcase → 3 → Primary → cards*
 */
export interface Hero2SliceStyle3PrimaryCardsItem {
  /**
   * image field in *ProductShowcase → 3 → Primary → cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style3.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *ProductShowcase → 3 → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style3.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * headline field in *ProductShowcase → 3 → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style3.primary.cards[].headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * description field in *ProductShowcase → 3 → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style3.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * type field in *ProductShowcase → 3 → Primary → cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: image
   * - **API ID Path**: hero_2.style3.primary.cards[].type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<"image" | "review" | "step", "filled">;
}

/**
 * Primary content in *ProductShowcase → 1 → Primary*
 */
export interface Hero2SliceDefaultPrimary {
  /**
   * headline field in *ProductShowcase → 1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero_2.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * description field in *ProductShowcase → 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *ProductShowcase → 1 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Description Align field in *ProductShowcase → 1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.description_align
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description_align: prismic.KeyTextField;

  /**
   * window field in *ProductShowcase → 1 → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_2.default.primary.window
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  window: prismic.BooleanField;

  /**
   * Call To Action Link field in *ProductShowcase → 1 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.call_to_action_link
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  call_to_action_link: prismic.ContentRelationshipField;

  /**
   * Call To Action Label field in *ProductShowcase → 1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.call_to_action_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  call_to_action_label: prismic.KeyTextField;

  /**
   * title field in *ProductShowcase → 1 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * cards field in *ProductShowcase → 1 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<Hero2SliceDefaultPrimaryCardsItem>>;

  /**
   * content field in *ProductShowcase → 1 → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: image
   * - **API ID Path**: hero_2.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  content: prismic.SelectField<"image" | "card", "filled">;

  /**
   * reverse field in *ProductShowcase → 1 → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_2.default.primary.reverse
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  reverse: prismic.BooleanField;
}

/**
 * 1 variation for ProductShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Hero2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Hero2SliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ProductShowcase → 2 → Primary*
 */
export interface Hero2SliceStyle2Primary {
  /**
   * headline field in *ProductShowcase → 2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero_2.style2.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * description field in *ProductShowcase → 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style2.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *ProductShowcase → 2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style2.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Description Align field in *ProductShowcase → 2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style2.primary.description_align
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description_align: prismic.KeyTextField;

  /**
   * window field in *ProductShowcase → 2 → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_2.style2.primary.window
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  window: prismic.BooleanField;

  /**
   * Call To Action Link field in *ProductShowcase → 2 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style2.primary.call_to_action_link
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  call_to_action_link: prismic.ContentRelationshipField;

  /**
   * Call To Action Label field in *ProductShowcase → 2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style2.primary.call_to_action_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  call_to_action_label: prismic.KeyTextField;

  /**
   * title field in *ProductShowcase → 2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style2.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * cards field in *ProductShowcase → 2 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style2.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<Hero2SliceStyle2PrimaryCardsItem>>;

  /**
   * content field in *ProductShowcase → 2 → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: image
   * - **API ID Path**: hero_2.style2.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  content: prismic.SelectField<"image" | "card", "filled">;

  /**
   * reverse field in *ProductShowcase → 2 → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_2.style2.primary.reverse
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  reverse: prismic.BooleanField;
}

/**
 * 2 variation for ProductShowcase Slice
 *
 * - **API ID**: `style2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Hero2SliceStyle2 = prismic.SharedSliceVariation<
  "style2",
  Simplify<Hero2SliceStyle2Primary>,
  never
>;

/**
 * Primary content in *ProductShowcase → 3 → Primary*
 */
export interface Hero2SliceStyle3Primary {
  /**
   * headline field in *ProductShowcase → 3 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero_2.style3.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * description field in *ProductShowcase → 3 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style3.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *ProductShowcase → 3 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style3.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Description Align field in *ProductShowcase → 3 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style3.primary.description_align
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description_align: prismic.KeyTextField;

  /**
   * window field in *ProductShowcase → 3 → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_2.style3.primary.window
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  window: prismic.BooleanField;

  /**
   * Call To Action Link field in *ProductShowcase → 3 → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style3.primary.call_to_action_link
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  call_to_action_link: prismic.ContentRelationshipField;

  /**
   * Call To Action Label field in *ProductShowcase → 3 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style3.primary.call_to_action_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  call_to_action_label: prismic.KeyTextField;

  /**
   * title field in *ProductShowcase → 3 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style3.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * cards field in *ProductShowcase → 3 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.style3.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<Hero2SliceStyle3PrimaryCardsItem>>;

  /**
   * content field in *ProductShowcase → 3 → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: image
   * - **API ID Path**: hero_2.style3.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  content: prismic.SelectField<"image" | "card", "filled">;

  /**
   * reverse field in *ProductShowcase → 3 → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_2.style3.primary.reverse
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  reverse: prismic.BooleanField;
}

/**
 * 3 variation for ProductShowcase Slice
 *
 * - **API ID**: `style3`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Hero2SliceStyle3 = prismic.SharedSliceVariation<
  "style3",
  Simplify<Hero2SliceStyle3Primary>,
  never
>;

/**
 * Slice variation for *ProductShowcase*
 */
type Hero2SliceVariation =
  | Hero2SliceDefault
  | Hero2SliceStyle2
  | Hero2SliceStyle3;

/**
 * ProductShowcase Shared Slice
 *
 * - **API ID**: `hero_2`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type Hero2Slice = prismic.SharedSlice<"hero_2", Hero2SliceVariation>;

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *Newsletter → Default → Primary*
 */
export interface NewsletterSliceDefaultPrimary {
  /**
   * title field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * cta button text field in *Newsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.default.primary.cta_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_button_text: prismic.KeyTextField;
}

/**
 * Default variation for Newsletter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsletterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Newsletter*
 */
type NewsletterSliceVariation = NewsletterSliceDefault;

/**
 * Newsletter Shared Slice
 *
 * - **API ID**: `newsletter`
 * - **Description**: Newsletter
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NewsletterSlice = prismic.SharedSlice<
  "newsletter",
  NewsletterSliceVariation
>;

/**
 * Item in *Sliders → blog → Primary → blogs*
 */
export interface SlidersSliceBlogPrimaryItemsItem {
  /**
   * blog field in *Sliders → blog → Primary → blogs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.blog.primary.items[].blog
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  blog: prismic.ContentRelationshipField<"blog">;
}

/**
 * Item in *Sliders → icon → Primary → icons*
 */
export interface SlidersSliceIconsPrimaryIconsItem {
  /**
   * image field in *Sliders → icon → Primary → icons*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.icons.primary.icons[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * image description field in *Sliders → icon → Primary → icons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.icons.primary.icons[].image_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_description: prismic.KeyTextField;
}

/**
 * Primary content in *Sliders → product → Primary*
 */
export interface SlidersSliceDefaultPrimary {
  /**
   * Slider Title field in *Sliders → product → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: sliders.default.primary.slider_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  slider_title: prismic.KeyTextField;

  /**
   * Object IDs field in *Sliders → product → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: id
   * - **API ID Path**: sliders.default.primary.object_ids
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  object_ids: prismic.KeyTextField;

  /**
   * sliderHeadline field in *Sliders → product → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.default.primary.sliderheadline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sliderheadline: prismic.KeyTextField;

  /**
   * imageFit field in *Sliders → product → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: contain
   * - **API ID Path**: sliders.default.primary.imagefit
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  imagefit: prismic.SelectField<"contain" | "cover", "filled">;
}

/**
 * product variation for Sliders Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SlidersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SlidersSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Sliders → blog → Primary*
 */
export interface SlidersSliceBlogPrimary {
  /**
   * Slider Title field in *Sliders → blog → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: sliders.blog.primary.slider_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  slider_title: prismic.KeyTextField;

  /**
   * sliderHeadline field in *Sliders → blog → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.blog.primary.sliderheadline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sliderheadline: prismic.KeyTextField;

  /**
   * blogs field in *Sliders → blog → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.blog.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<SlidersSliceBlogPrimaryItemsItem>>;

  /**
   * imageFit field in *Sliders → blog → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: contain
   * - **API ID Path**: sliders.blog.primary.imagefit
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  imagefit: prismic.SelectField<"contain" | "cover", "filled">;
}

/**
 * blog variation for Sliders Slice
 *
 * - **API ID**: `blog`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SlidersSliceBlog = prismic.SharedSliceVariation<
  "blog",
  Simplify<SlidersSliceBlogPrimary>,
  never
>;

/**
 * Primary content in *Sliders → icon → Primary*
 */
export interface SlidersSliceIconsPrimary {
  /**
   * Slider Title field in *Sliders → icon → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: sliders.icons.primary.slider_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  slider_title: prismic.KeyTextField;

  /**
   * sliderHeadline field in *Sliders → icon → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.icons.primary.sliderheadline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sliderheadline: prismic.KeyTextField;

  /**
   * imageFit field in *Sliders → icon → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: contain
   * - **API ID Path**: sliders.icons.primary.imagefit
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  imagefit: prismic.SelectField<"contain" | "cover", "filled">;

  /**
   * icons field in *Sliders → icon → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sliders.icons.primary.icons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  icons: prismic.GroupField<Simplify<SlidersSliceIconsPrimaryIconsItem>>;
}

/**
 * icon variation for Sliders Slice
 *
 * - **API ID**: `icons`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SlidersSliceIcons = prismic.SharedSliceVariation<
  "icons",
  Simplify<SlidersSliceIconsPrimary>,
  never
>;

/**
 * Slice variation for *Sliders*
 */
type SlidersSliceVariation =
  | SlidersSliceDefault
  | SlidersSliceBlog
  | SlidersSliceIcons;

/**
 * Sliders Shared Slice
 *
 * - **API ID**: `sliders`
 * - **Description**: Sliders
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SlidersSlice = prismic.SharedSlice<
  "sliders",
  SlidersSliceVariation
>;

/**
 * Primary content in *SocialMediaLinks → Items*
 */
export interface SocialMediaLinksSliceDefaultItem {
  /**
   * Social Media Handle field in *SocialMediaLinks → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_links.items[].social_media_handle
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_media_handle: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for SocialMediaLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SocialMediaLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SocialMediaLinksSliceDefaultItem>
>;

/**
 * Slice variation for *SocialMediaLinks*
 */
type SocialMediaLinksSliceVariation = SocialMediaLinksSliceDefault;

/**
 * SocialMediaLinks Shared Slice
 *
 * - **API ID**: `social_media_links`
 * - **Description**: SocialMediaLinks
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SocialMediaLinksSlice = prismic.SharedSlice<
  "social_media_links",
  SocialMediaLinksSliceVariation
>;

/**
 * Item in *TestimonialGallery → Default → Primary → Gallery Images*
 */
export interface TestimonialGallerySliceDefaultPrimaryGalleryImagesItem {
  /**
   * Image field in *TestimonialGallery → Default → Primary → Gallery Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_gallery.default.primary.gallery_images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *TestimonialGallery → Default → Primary → Testimonials*
 */
export interface TestimonialGallerySliceDefaultPrimaryTestimonialsItem {
  /**
   * Rating Count field in *TestimonialGallery → Default → Primary → Testimonials*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_gallery.default.primary.testimonials[].rating_count
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rating_count: prismic.NumberField;

  /**
   * Quote field in *TestimonialGallery → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_gallery.default.primary.testimonials[].quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Author Name field in *TestimonialGallery → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_gallery.default.primary.testimonials[].author_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * title field in *TestimonialGallery → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_gallery.default.primary.testimonials[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *TestimonialGallery → Default → Primary*
 */
export interface TestimonialGallerySliceDefaultPrimary {
  /**
   * Heading field in *TestimonialGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_gallery.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *TestimonialGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_gallery.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Gallery Images field in *TestimonialGallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_gallery.default.primary.gallery_images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery_images: prismic.GroupField<
    Simplify<TestimonialGallerySliceDefaultPrimaryGalleryImagesItem>
  >;

  /**
   * Testimonials field in *TestimonialGallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_gallery.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialGallerySliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Default variation for TestimonialGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestimonialGallery*
 */
type TestimonialGallerySliceVariation = TestimonialGallerySliceDefault;

/**
 * TestimonialGallery Shared Slice
 *
 * - **API ID**: `testimonial_gallery`
 * - **Description**: Customer testimonials with gallery and reviews
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialGallerySlice = prismic.SharedSlice<
  "testimonial_gallery",
  TestimonialGallerySliceVariation
>;

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

/**
 * Primary content in *WindowPanels → Items*
 */
export interface WindowPanelsSliceDefaultItem {
  /**
   * Window BG field in *WindowPanels → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: window_panels.items[].window_bg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  window_bg: prismic.ImageField<never>;

  /**
   * Review field in *WindowPanels → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: window_panels.items[].review
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  review: prismic.ContentRelationshipField;
}

/**
 * Default variation for WindowPanels Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WindowPanelsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<WindowPanelsSliceDefaultItem>
>;

/**
 * Primary content in *WindowPanels → doubled-up → Primary*
 */
export interface WindowPanelsSliceDoubledUpPrimary {
  /**
   * Double Up WIndow field in *WindowPanels → doubled-up → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: window_panels.doubledUp.primary.double_up_window
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  double_up_window: prismic.NumberField;
}

/**
 * Primary content in *WindowPanels → Items*
 */
export interface WindowPanelsSliceDoubledUpItem {
  /**
   * Window BG field in *WindowPanels → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: window_panels.items[].window_bg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  window_bg: prismic.ImageField<never>;

  /**
   * Review field in *WindowPanels → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: window_panels.items[].review
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  review: prismic.ContentRelationshipField;
}

/**
 * doubled-up variation for WindowPanels Slice
 *
 * - **API ID**: `doubledUp`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WindowPanelsSliceDoubledUp = prismic.SharedSliceVariation<
  "doubledUp",
  Simplify<WindowPanelsSliceDoubledUpPrimary>,
  Simplify<WindowPanelsSliceDoubledUpItem>
>;

/**
 * Slice variation for *WindowPanels*
 */
type WindowPanelsSliceVariation =
  | WindowPanelsSliceDefault
  | WindowPanelsSliceDoubledUp;

/**
 * WindowPanels Shared Slice
 *
 * - **API ID**: `window_panels`
 * - **Description**: WindowPanels
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WindowPanelsSlice = prismic.SharedSlice<
  "window_panels",
  WindowPanelsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      BlogPostDocumentDataSectionsItem,
      BlogPostDocumentDataSlices2Slice,
      CategorylinkDocument,
      CategorylinkDocumentData,
      ComingSoonDocument,
      ComingSoonDocumentData,
      ComingSoonDocumentDataSlicesSlice,
      ContentDocument,
      ContentDocumentData,
      ContentDocumentDataFeaturesItem,
      CtaEmailDocument,
      CtaEmailDocumentData,
      CtaEmailDocumentDataSlicesSlice,
      CustomerReviewDocument,
      CustomerReviewDocumentData,
      FooterNavigationDocument,
      FooterNavigationDocumentData,
      FooterNavigationDocumentDataNavsItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavsItem,
      HeaderDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      ProductContentDocument,
      ProductContentDocumentData,
      ProductContentDocumentDataFeaturesItem,
      ProductContentDocumentDataShowcasesItem,
      ProductLandingPageDocument,
      ProductLandingPageDocumentData,
      ProductLandingPageDocumentDataQuickPointsItem,
      ProductLandingPageDocumentDataSlicesSlice,
      SocialMediaHandleDocument,
      SocialMediaHandleDocumentData,
      SocialMediaLinksDocument,
      SocialMediaLinksDocumentData,
      SocialMediaLinksDocumentDataSlicesSlice,
      ThePlaygroundDisplayLogoDocument,
      ThePlaygroundDisplayLogoDocumentData,
      AllDocumentTypes,
      BenefitsCalloutSlice,
      BenefitsCalloutSliceDefaultPrimaryBenefitsItem,
      BenefitsCalloutSliceDefaultPrimary,
      BenefitsCalloutSliceVariation,
      BenefitsCalloutSliceDefault,
      BlockQuoteSlice,
      BlockQuoteSliceVariation,
      BlockQuoteSliceDefault,
      BlogTextSlice,
      BlogTextSliceVariation,
      BlogTextSliceDefault,
      DropListSlice,
      DropListSliceDefaultPrimaryDropitemsItem,
      DropListSliceDefaultPrimary,
      DropListSliceVariation,
      DropListSliceDefault,
      FaqAccordionSlice,
      FaqAccordionSliceDefaultPrimaryFaqItemsItem,
      FaqAccordionSliceDefaultPrimary,
      FaqAccordionSliceVariation,
      FaqAccordionSliceDefault,
      FeaturedCategoriesSlice,
      FeaturedCategoriesSliceDefaultItem,
      FeaturedCategoriesSliceVariation,
      FeaturedCategoriesSliceDefault,
      HeaderSlice,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceCarouselPrimary,
      HeroSliceCarouselItem,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceCarousel,
      Hero2Slice,
      Hero2SliceDefaultPrimaryCardsItem,
      Hero2SliceDefaultPrimary,
      Hero2SliceStyle2PrimaryCardsItem,
      Hero2SliceStyle2Primary,
      Hero2SliceStyle3PrimaryCardsItem,
      Hero2SliceStyle3Primary,
      Hero2SliceVariation,
      Hero2SliceDefault,
      Hero2SliceStyle2,
      Hero2SliceStyle3,
      ImageSlice,
      ImageSliceVariation,
      ImageSliceDefault,
      NewsletterSlice,
      NewsletterSliceDefaultPrimary,
      NewsletterSliceVariation,
      NewsletterSliceDefault,
      SlidersSlice,
      SlidersSliceDefaultPrimary,
      SlidersSliceBlogPrimaryItemsItem,
      SlidersSliceBlogPrimary,
      SlidersSliceIconsPrimaryIconsItem,
      SlidersSliceIconsPrimary,
      SlidersSliceVariation,
      SlidersSliceDefault,
      SlidersSliceBlog,
      SlidersSliceIcons,
      SocialMediaLinksSlice,
      SocialMediaLinksSliceDefaultItem,
      SocialMediaLinksSliceVariation,
      SocialMediaLinksSliceDefault,
      TestimonialGallerySlice,
      TestimonialGallerySliceDefaultPrimaryGalleryImagesItem,
      TestimonialGallerySliceDefaultPrimaryTestimonialsItem,
      TestimonialGallerySliceDefaultPrimary,
      TestimonialGallerySliceVariation,
      TestimonialGallerySliceDefault,
      VideoSlice,
      VideoSliceVariation,
      VideoSliceDefault,
      WindowPanelsSlice,
      WindowPanelsSliceDefaultItem,
      WindowPanelsSliceDoubledUpPrimary,
      WindowPanelsSliceDoubledUpItem,
      WindowPanelsSliceVariation,
      WindowPanelsSliceDefault,
      WindowPanelsSliceDoubledUp,
    };
  }
}
