// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for CategoryLink documents
 */
interface CategorylinkDocumentData {
  /**
   * Title field in *CategoryLink*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: categorylink.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *CategoryLink*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: categorylink.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * CategoryLink document from Prismic
 *
 * - **API ID**: `categorylink`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategorylinkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategorylinkDocumentData>,
    "categorylink",
    Lang
  >;

type ComingSoonDocumentDataSlicesSlice =
  | SocialMediaLinksSlice
  | HeroSlice
  | CallToActionSlice;

/**
 * Content for Coming Soon documents
 */
interface ComingSoonDocumentData {
  /**
   * Slice Zone field in *Coming Soon*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: coming_soon.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ComingSoonDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Coming Soon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: coming_soon.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Coming Soon*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: coming_soon.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Coming Soon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: coming_soon.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Coming Soon document from Prismic
 *
 * - **API ID**: `coming_soon`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ComingSoonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ComingSoonDocumentData>,
    "coming_soon",
    Lang
  >;

type CtaEmailDocumentDataSlicesSlice = CallToActionSlice;

/**
 * Content for CTA documents
 */
interface CtaEmailDocumentData {
  /**
   * Paragraph field in *CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_email.paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Button Label field in *CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_email.button_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Form Placeholder field in *CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_email.form_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_placeholder: prismic.KeyTextField;

  /**
   * Slice Zone field in *CTA*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_email.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CtaEmailDocumentDataSlicesSlice>;
}

/**
 * CTA document from Prismic
 *
 * - **API ID**: `cta_email`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CtaEmailDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CtaEmailDocumentData>,
    "cta_email",
    Lang
  >;

/**
 * Item in *HeaderNavigation → Navs*
 */
export interface HeaderDocumentDataNavsItem {
  /**
   * Nav field in *HeaderNavigation → Navs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navs[].nav
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nav: prismic.ContentRelationshipField;
}

/**
 * Content for HeaderNavigation documents
 */
interface HeaderDocumentData {
  /**
   * Navs field in *HeaderNavigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navs: prismic.GroupField<Simplify<HeaderDocumentDataNavsItem>>;
}

/**
 * HeaderNavigation document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HeaderDocumentData>, "header", Lang>;

type HomepageDocumentDataSlicesSlice =
  | FeaturedCategoriesSlice
  | Hero2Slice
  | HeroSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for Social Media Handle documents
 */
interface SocialMediaHandleDocumentData {
  /**
   * Social Media Name field in *Social Media Handle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_handle.social_media_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  social_media_name: prismic.KeyTextField;

  /**
   * Social Media Url field in *Social Media Handle*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_handle.social_media_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  social_media_url: prismic.KeyTextField;

  /**
   * Social Media Logo field in *Social Media Handle*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_handle.social_media_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_media_logo: prismic.ImageField<never>;
}

/**
 * Social Media Handle document from Prismic
 *
 * - **API ID**: `social_media_handle`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialMediaHandleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SocialMediaHandleDocumentData>,
    "social_media_handle",
    Lang
  >;

type SocialMediaLinksDocumentDataSlicesSlice = SocialMediaLinksSlice;

/**
 * Content for Social Media Handles documents
 */
interface SocialMediaLinksDocumentData {
  /**
   * Slice Zone field in *Social Media Handles*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_links.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SocialMediaLinksDocumentDataSlicesSlice>;
}

/**
 * Social Media Handles document from Prismic
 *
 * - **API ID**: `social_media_links`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialMediaLinksDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SocialMediaLinksDocumentData>,
    "social_media_links",
    Lang
  >;

export type AllDocumentTypes =
  | CategorylinkDocument
  | ComingSoonDocument
  | CtaEmailDocument
  | HeaderDocument
  | HomepageDocument
  | SocialMediaHandleDocument
  | SocialMediaLinksDocument;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Call Description field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.call_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_description: prismic.KeyTextField;

  /**
   * Action Button Text field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.action_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  action_button_text: prismic.KeyTextField;

  /**
   * Form Placeholder Text field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.form_placeholder_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_placeholder_text: prismic.KeyTextField;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceOnlyButtonPrimary {
  /**
   * Action Button Text field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.action_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  action_button_text: prismic.KeyTextField;
}

/**
 * OnlyButton variation for CallToAction Slice
 *
 * - **API ID**: `onlyButton`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceOnlyButton = prismic.SharedSliceVariation<
  "onlyButton",
  Simplify<CallToActionSliceOnlyButtonPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation =
  | CallToActionSliceDefault
  | CallToActionSliceOnlyButton;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *CallToAction2 → Primary*
 */
export interface CallToAction2SliceDefaultPrimary {
  /**
   * Image field in *CallToAction2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_2.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *CallToAction2 → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_2.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * paragraph field in *CallToAction2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_2.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * buttonLink field in *CallToAction2 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Redirect URL for CTA button
   * - **API ID Path**: call_to_action_2.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * buttonLabel field in *CallToAction2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Label for CTA button
   * - **API ID Path**: call_to_action_2.primary.buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField;
}

/**
 * Default variation for CallToAction2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToAction2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToAction2SliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CallToAction2 → Primary*
 */
export interface CallToAction2SliceAlignLeftPrimary {
  /**
   * Image field in *CallToAction2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_2.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *CallToAction2 → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_2.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * paragraph field in *CallToAction2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_2.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * buttonLink field in *CallToAction2 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Redirect URL for CTA button
   * - **API ID Path**: call_to_action_2.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * buttonLabel field in *CallToAction2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Label for CTA button
   * - **API ID Path**: call_to_action_2.primary.buttonLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonLabel: prismic.KeyTextField;
}

/**
 * AlignLeft variation for CallToAction2 Slice
 *
 * - **API ID**: `alignLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToAction2SliceAlignLeft = prismic.SharedSliceVariation<
  "alignLeft",
  Simplify<CallToAction2SliceAlignLeftPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction2*
 */
type CallToAction2SliceVariation =
  | CallToAction2SliceDefault
  | CallToAction2SliceAlignLeft;

/**
 * CallToAction2 Shared Slice
 *
 * - **API ID**: `call_to_action_2`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToAction2Slice = prismic.SharedSlice<
  "call_to_action_2",
  CallToAction2SliceVariation
>;

/**
 * Primary content in *FeaturedCategories → Items*
 */
export interface FeaturedCategoriesSliceDefaultItem {
  /**
   * Category field in *FeaturedCategories → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_categories.items[].category
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField;
}

/**
 * Default variation for FeaturedCategories Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedCategoriesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<FeaturedCategoriesSliceDefaultItem>
>;

/**
 * Slice variation for *FeaturedCategories*
 */
type FeaturedCategoriesSliceVariation = FeaturedCategoriesSliceDefault;

/**
 * FeaturedCategories Shared Slice
 *
 * - **API ID**: `featured_categories`
 * - **Description**: FeaturedCategories
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedCategoriesSlice = prismic.SharedSlice<
  "featured_categories",
  FeaturedCategoriesSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Hero Title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_title: prismic.KeyTextField;

  /**
   * Hero Description field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_description: prismic.KeyTextField;

  /**
   * Hero BG Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_bg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_bg_image: prismic.ImageField<never>;

  /**
   * Content Alignment field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.content_alignment
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content_alignment: prismic.KeyTextField;

  /**
   * Use Logo field in *Hero → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.primary.use_logo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  use_logo: prismic.BooleanField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceHeroWithSocialMediaHandlesPrimary {
  /**
   * Hero Title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_title: prismic.KeyTextField;

  /**
   * Hero Description field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_description: prismic.KeyTextField;

  /**
   * Content Alignment field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.content_alignment
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content_alignment: prismic.KeyTextField;

  /**
   * Hero BG Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_bg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_bg_image: prismic.ImageField<never>;

  /**
   * Use Logo field in *Hero → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.primary.use_logo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  use_logo: prismic.BooleanField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceHeroWithSocialMediaHandlesItem {
  /**
   * Social Media Handle field in *Hero → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].social_media_handle
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_media_handle: prismic.ContentRelationshipField;
}

/**
 * HeroWithSocialMediaHandles variation for Hero Slice
 *
 * - **API ID**: `heroWithSocialMediaHandles`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroWithSocialMediaHandles = prismic.SharedSliceVariation<
  "heroWithSocialMediaHandles",
  Simplify<HeroSliceHeroWithSocialMediaHandlesPrimary>,
  Simplify<HeroSliceHeroWithSocialMediaHandlesItem>
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceHandlesCtaPrimary {
  /**
   * Hero Title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_title: prismic.KeyTextField;

  /**
   * Hero Description field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_description: prismic.KeyTextField;

  /**
   * CTA field in *Hero → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.ContentRelationshipField;

  /**
   * Hero BG Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_bg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_bg_image: prismic.ImageField<never>;

  /**
   * Content Alignment field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.content_alignment
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content_alignment: prismic.KeyTextField;

  /**
   * Use Logo field in *Hero → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.primary.use_logo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  use_logo: prismic.BooleanField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceHandlesCtaItem {
  /**
   * Social Media Handle field in *Hero → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].social_media_handle
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_media_handle: prismic.ContentRelationshipField;
}

/**
 * Handles & CTA variation for Hero Slice
 *
 * - **API ID**: `handlesCta`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHandlesCta = prismic.SharedSliceVariation<
  "handlesCta",
  Simplify<HeroSliceHandlesCtaPrimary>,
  Simplify<HeroSliceHandlesCtaItem>
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceWithCtaPrimary {
  /**
   * Hero Title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_title: prismic.KeyTextField;

  /**
   * Hero Description field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_description: prismic.KeyTextField;

  /**
   * CTA field in *Hero → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.ContentRelationshipField;

  /**
   * Hero BG Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero_bg_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_bg_image: prismic.ImageField<never>;

  /**
   * Content Alignment field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.content_alignment
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content_alignment: prismic.KeyTextField;

  /**
   * Use Logo field in *Hero → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.primary.use_logo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  use_logo: prismic.BooleanField;
}

/**
 * WithCta variation for Hero Slice
 *
 * - **API ID**: `withCta`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceWithCta = prismic.SharedSliceVariation<
  "withCta",
  Simplify<HeroSliceWithCtaPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceHeroWithSocialMediaHandles
  | HeroSliceHandlesCta
  | HeroSliceWithCta;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ProductShowcase → Primary*
 */
export interface Hero2SliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero_2.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * callToActionLabel field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField;

  /**
   * callToActionLink field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;
}

/**
 * Default variation for ProductShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Hero2SliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ProductShowcase → Primary*
 */
export interface Hero2SliceImageRightPrimary {
  /**
   * eyebrowHeadline field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: hero_2.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * callToActionLabel field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField;

  /**
   * callToActionLink field in *ProductShowcase → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_2.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;
}

/**
 * Image Right variation for ProductShowcase Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero2SliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<Hero2SliceImageRightPrimary>,
  never
>;

/**
 * Slice variation for *ProductShowcase*
 */
type Hero2SliceVariation = Hero2SliceDefault | Hero2SliceImageRight;

/**
 * ProductShowcase Shared Slice
 *
 * - **API ID**: `hero_2`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero2Slice = prismic.SharedSlice<"hero_2", Hero2SliceVariation>;

/**
 * Primary content in *SocialMediaLinks → Items*
 */
export interface SocialMediaLinksSliceDefaultItem {
  /**
   * Social Media Handle field in *SocialMediaLinks → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media_links.items[].social_media_handle
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_media_handle: prismic.LinkField;
}

/**
 * Default variation for SocialMediaLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialMediaLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SocialMediaLinksSliceDefaultItem>
>;

/**
 * Slice variation for *SocialMediaLinks*
 */
type SocialMediaLinksSliceVariation = SocialMediaLinksSliceDefault;

/**
 * SocialMediaLinks Shared Slice
 *
 * - **API ID**: `social_media_links`
 * - **Description**: SocialMediaLinks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialMediaLinksSlice = prismic.SharedSlice<
  "social_media_links",
  SocialMediaLinksSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CategorylinkDocument,
      CategorylinkDocumentData,
      ComingSoonDocument,
      ComingSoonDocumentData,
      ComingSoonDocumentDataSlicesSlice,
      CtaEmailDocument,
      CtaEmailDocumentData,
      CtaEmailDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavsItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      SocialMediaHandleDocument,
      SocialMediaHandleDocumentData,
      SocialMediaLinksDocument,
      SocialMediaLinksDocumentData,
      SocialMediaLinksDocumentDataSlicesSlice,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceOnlyButtonPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CallToActionSliceOnlyButton,
      CallToAction2Slice,
      CallToAction2SliceDefaultPrimary,
      CallToAction2SliceAlignLeftPrimary,
      CallToAction2SliceVariation,
      CallToAction2SliceDefault,
      CallToAction2SliceAlignLeft,
      FeaturedCategoriesSlice,
      FeaturedCategoriesSliceDefaultItem,
      FeaturedCategoriesSliceVariation,
      FeaturedCategoriesSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceHeroWithSocialMediaHandlesPrimary,
      HeroSliceHeroWithSocialMediaHandlesItem,
      HeroSliceHandlesCtaPrimary,
      HeroSliceHandlesCtaItem,
      HeroSliceWithCtaPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceHeroWithSocialMediaHandles,
      HeroSliceHandlesCta,
      HeroSliceWithCta,
      Hero2Slice,
      Hero2SliceDefaultPrimary,
      Hero2SliceImageRightPrimary,
      Hero2SliceVariation,
      Hero2SliceDefault,
      Hero2SliceImageRight,
      SocialMediaLinksSlice,
      SocialMediaLinksSliceDefaultItem,
      SocialMediaLinksSliceVariation,
      SocialMediaLinksSliceDefault,
    };
  }
}
