import { getCatalogObjects } from "api/catalogApi";
import Footer from "components/Footer";
import Header from "components/Header";
import Providers from "components/Providers";

import "styles/globals.scss";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }) {
  const categoryItems = await getCatalogObjects("CATEGORY");

  const splitNames = ({ objects }) =>
    objects?.map(({ categoryData: { name } }) => name.split(" "));

  return (
    <html lang="en">
      <body className="relative">
        <Providers apparelCategories={splitNames(categoryItems)}>
          <Header />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}