import Footer from "components/Footer";
import Header from "components/Header";
import MainLayout from "components/MainLayout";
import Providers from "components/Providers";

import "styles/globals.scss";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          <Providers>{children}</Providers>
        </main>
        <Footer />
      </body>
    </html>
  );
}
