// export const contentTranslations = {
//   startTop: "translate-x-0 translate-y-0",
//   startThird: "translate-x-full translate-y-1/3",
//   startMiddle: "translate-x-1/2 translate-y-0",
//   startThirdQuarter: "translate-x-full translate-y-3/4",
//   startEnd: "translate-x-full translate-y-0",
//   centerTop: "translate-x-0 translate-y-1/2",
//   centerThird: "translate-x-full translate-y-1/2",
//   centerMiddle: "translate-x-1/2 translate-y-1/2",
//   centerThirdQuarter: "translate-x-full translate-y-full",
//   centerEnd: "translate-x-full translate-y-1/2",
//   bottomTop: "translate-x-full translate-y-0",
//   bottomThird: "translate-x-full translate-y-1/3",
//   bottomMiddle: "translate-x-full translate-y-1/2",
//   bottomThirdQuarter: "translate-x-full translate-y-3/4",
//   bottomEnd: "translate-x-full translate-y-full",
// };
export const contentPositions: {[id: string]: string} = {
  topStart: "left-0 top-0",
  topQuarter: "left-1/4 top-0 -translate-x-1/4",
  topCenter: "left-1/2 top-0 -translate-x-1/2",
  topThirdQuarter: "left-3/4 top-0  -translate-x-3/4",
  topEnd: "right-0 top-0",
  middleStart: "left-0 top-1/2",
  middleQuarter: "left-1/4 top-1/2 -translate-x-1/4 -translate-y-1/2",
  middleCenter: "left-1/2 top-1/2 -translate-x-1/2",
  middleThirdQuarter: "left-3/4 top-1/2 -translate-x-3/4 -translate-y-1/2",
  middleEnd: "right-0 top-1/2",
  bottomStart: "left-0 bottom-1/4",
  bottomQuarter: "left-1/4 bottom-1/4 -translate-x-1/4",
  bottomCenter: "left-1/2 bottom-1/4 -translate-x-1/2",
  bottomThirdQuarter: "left-3/4 bottom-1/4 -translate-x-3/4",
  bottomEnd: "right-0 bottom-1/4",
};

export const alignToFlexMapping: { [key: string]: string } = {
  left: "start",
  center: "center",
  right: "end",
} as const;
