// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  benefits_callout: dynamic(() => import("./BenefitsCallout")),
  drop_list: dynamic(() => import("./DropList")),
  faq_accordion: dynamic(() => import("./FaqAccordion")),
  featured_categories: dynamic(() => import("./FeaturedCategories")),
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  hero_2: dynamic(() => import("./ProductShowcase")),
  newsletter: dynamic(() => import("./Newsletter")),
  sliders: dynamic(() => import("./Sliders")),
  social_media_links: dynamic(() => import("./SocialMediaLinks")),
  testimonial_gallery: dynamic(() => import("./TestimonialGallery")),
  window_panels: dynamic(() => import("./WindowPanels")),
};
