// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  call_to_action_2: dynamic(() => import("./CallToAction2")),
  featured_categories: dynamic(() => import("./FeaturedCategories")),
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  hero_2: dynamic(() => import("./ProductShowcase")),
  social_media_links: dynamic(() => import("./SocialMediaLinks")),
  window_panels: dynamic(() => import("./WindowPanels")),
};
