// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  call_to_action_2: dynamic(() => import("./CallToAction2")),
  hero: dynamic(() => import("./Hero")),
  social_media_links: dynamic(() => import("./SocialMediaLinks")),
};
